import { createElement as h } from 'react'
import { css } from '../lib/css'
import { Icon } from '../lib/Icon'
import { SparkleIcon } from '../components/brandIcons'
import { useWorkspace } from '../state/WorkspaceContext'
import { ThoughtChain } from '../components/ai/ThoughtChain'
import { SPCDashboard } from '../components/SPCDashboard'

export function Cowork() {
  const V = useWorkspace()
  return h('div', { style: css('height:100%;display:flex;min-height:0;background:var(--erd-color-bg-layout)') },
    // ---- history rail ----
    V.cwHistoryOpen ? h('div', { style: css('width:238px;flex:none;display:flex;flex-direction:column;background:#fafafa;border-right:1px solid var(--erd-color-border-secondary)') },
      h('div', { style: css('padding:14px 12px 8px;display:flex;align-items:center;justify-content:space-between') },
        h('span', { style: css('font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.4px;color:var(--erd-color-text-tertiary);padding-left:4px') }, 'Chats'),
        h('span', { className: 'erd-icon-btn', onClick: V.cwToggleHistory, title: 'Collapse chats', style: css('width:26px;height:26px;display:flex;align-items:center;justify-content:center;border-radius:6px;cursor:pointer;color:var(--erd-color-text-tertiary);font-size:15px') }, Icon('ant-design:menu-fold-outlined'))),
      h('div', { style: css('padding:0 12px 10px') },
        h('div', { className: 'erd-icon-btn', onClick: V.cwNewSession, style: css('display:flex;align-items:center;justify-content:center;gap:8px;height:36px;border-radius:8px;cursor:pointer;font-size:13px;font-weight:500;background:var(--erd-color-primary);color:#fff') }, Icon('ant-design:plus-outlined'), 'New chat')),
      h('div', { style: css('flex:1;overflow-y:auto;padding:0 8px 10px;display:flex;flex-direction:column;gap:2px') },
        V.cwSessions.map((c) => h('div', { key: c.id, className: 'erd-navrow', onClick: c.onSelect, style: c.rowStyle },
          h('div', { style: css('display:flex;align-items:center;gap:8px;font-size:13px;font-weight:500;color:var(--erd-color-text);white-space:nowrap;overflow:hidden;text-overflow:ellipsis') }, Icon('ant-design:message-outlined', 'font-size:13px;color:var(--erd-color-text-tertiary);flex:none'), c.title),
          h('div', { style: css('font-size:11px;color:var(--erd-color-text-tertiary);padding-left:21px') }, c.time))))) : null,

    // ---- composer column ----
    h('div', { style: css('flex:1;min-width:360px;max-width:560px;display:flex;flex-direction:column;background:#fff;border-right:1px solid var(--erd-color-border-secondary)') },
      h('div', { style: css('padding:13px 20px;border-bottom:1px solid var(--erd-color-border-secondary);flex:none;display:flex;align-items:center;gap:11px') },
        V.cwHistoryClosed ? h('span', { className: 'erd-icon-btn', onClick: V.cwToggleHistory, title: 'Show chats', style: css('width:32px;height:32px;display:flex;align-items:center;justify-content:center;border-radius:7px;cursor:pointer;color:var(--erd-color-text-secondary);font-size:16px;border:1px solid var(--erd-color-border);flex:none') }, Icon('ant-design:menu-unfold-outlined')) : null,
        h('div', { style: css('flex:1;min-width:0') },
          h('div', { style: css('display:flex;align-items:center;gap:9px;font-weight:600;font-size:15px') }, h(SparkleIcon, { size: 20, fill: 'var(--erd-color-primary)' }), 'Cowork · Data studio'),
          h('div', { style: css('font-size:12px;color:var(--erd-color-text-tertiary);margin-top:3px') }, 'Import data, prompt eRD AI, get a dashboard or a deck.')),
        h('div', { style: css('display:flex;align-items:center;gap:8px;flex:none') },
          h('div', { style: css('font-size:11px;color:var(--erd-color-text-secondary);background:var(--erd-color-fill-tertiary);padding:5px 9px;border-radius:12px;display:inline-flex;align-items:center;gap:5px;max-width:148px') }, Icon('ant-design:database-outlined', 'font-size:12px;color:var(--erd-color-text-tertiary);flex:none'), h('span', { style: css('white-space:nowrap;overflow:hidden;text-overflow:ellipsis') }, V.cwSource)),
          h('div', { style: css('position:relative;flex:none') },
            h('div', { className: 'erd-icon-btn', onClick: V.cwToggleFilesPopover, title: 'Attachments', style: css('position:relative;width:34px;height:34px;display:flex;align-items:center;justify-content:center;border-radius:8px;cursor:pointer;color:var(--erd-color-text-secondary);font-size:17px;border:1px solid var(--erd-color-border)') },
              Icon('ant-design:paper-clip-outlined'),
              V.cwHasFiles ? h('span', { style: css('position:absolute;top:-5px;right:-5px;min-width:16px;height:16px;padding:0 3px;background:var(--erd-color-primary);color:#fff;border-radius:8px;font-size:9px;font-weight:600;display:flex;align-items:center;justify-content:center;border:1.5px solid #fff') }, V.cwFileCount) : null),
            V.cwFilesPopover ? h('div', null,
              h('div', { onClick: V.cwCloseFilesPopover, style: css('position:fixed;inset:0;z-index:35') }),
              h('div', { style: css('position:absolute;top:42px;right:0;width:290px;background:#fff;border:1px solid var(--erd-color-border-secondary);border-radius:11px;box-shadow:0 6px 24px rgba(0,0,0,.14);z-index:40;overflow:hidden') },
                h('div', { style: css('padding:11px 14px;border-bottom:1px solid var(--erd-color-border-secondary);display:flex;align-items:center;justify-content:space-between') },
                  h('span', { style: css('font-size:12px;font-weight:600') }, 'Attachments'),
                  h('span', { style: css('font-size:11px;color:var(--erd-color-text-tertiary)') }, V.cwFileCount + '/5 · ' + V.cwTotalSize)),
                h('div', { style: css('max-height:220px;overflow-y:auto') },
                  V.cwFiles.map((f, i) => h('div', { key: i, style: css('display:flex;align-items:center;gap:9px;padding:9px 12px;border-bottom:1px solid var(--erd-color-fill-quaternary)') },
                    Icon({ icon: f.icon, style: 'font-size:17px;color:' + f.color + ';flex:none' }),
                    h('div', { style: css('flex:1;min-width:0') }, h('div', { style: css('font-size:12.5px;font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis') }, f.name), h('div', { style: css('font-size:10.5px;color:var(--erd-color-text-tertiary)') }, f.meta)),
                    h('span', { className: 'erd-fav-remove', onClick: f.onRemove, style: css('width:22px;height:22px;display:flex;align-items:center;justify-content:center;border-radius:6px;color:var(--erd-color-text-quaternary);font-size:12px;cursor:pointer') }, Icon('ant-design:close-outlined')))),
                  V.cwNoFiles ? h('div', { style: css('padding:18px 14px;text-align:center;font-size:12px;color:var(--erd-color-text-tertiary)') }, 'No files attached yet.') : null),
                h('div', { style: css('padding:9px 12px;border-top:1px solid var(--erd-color-border-secondary)') },
                  h('div', { className: 'erd-icon-btn', onClick: V.cwOpenUpload, style: css('display:flex;align-items:center;justify-content:center;gap:7px;height:34px;border-radius:8px;cursor:pointer;font-size:12.5px;font-weight:500;color:var(--erd-color-primary);background:var(--erd-color-primary-bg)') }, Icon('ant-design:plus-outlined'), 'Attach files')))) : null))),

      // thread
      h('div', { id: 'cwThreadScroll', style: css('flex:1;overflow-y:auto;min-height:0;padding:16px 20px;display:flex;flex-direction:column;gap:14px') },
        V.cwThread.map((m) => h('div', { key: m.id },
          m.isAI ? h('div', { style: css('display:flex;align-items:center;gap:7px;margin-bottom:5px;font-size:11px;font-weight:600;color:var(--erd-color-text-secondary)') }, h(SparkleIcon, { size: 14, fill: 'var(--erd-color-primary)' }), 'eRD AI') : null,
          h('div', { style: m.rowStyle },
            h('div', { style: m.bubbleStyle },
              m.hasSteps ? h('div', { style: css('margin-bottom:9px;border:1px solid var(--erd-color-border-secondary);border-radius:10px;overflow:hidden;background:#fff') },
                h('div', { className: 'erd-navrow', onClick: m.onToggleSteps, style: css('display:flex;align-items:center;gap:8px;padding:8px 11px;cursor:pointer;font-size:12px;color:var(--erd-color-text-secondary)') },
                  Icon('ant-design:check-circle-fill', 'color:var(--erd-color-success);font-size:14px'),
                  h('span', { style: css('font-weight:500') }, m.stepsSummary),
                  Icon(m.stepsChevron, 'margin-left:auto;color:var(--erd-color-text-tertiary);font-size:11px')),
                m.stepsOpen ? h('div', { style: css('padding:8px 12px 12px;border-top:1px solid var(--erd-color-border-secondary)') }, h(ThoughtChain, { items: m.stepItems })) : null) : null,
              m.text,
              m.hasArtifact ? h('div', { style: css('display:flex;align-items:center;gap:8px;margin-top:9px;padding:8px 10px;background:#fff;border:1px solid var(--erd-color-border-secondary);border-radius:8px') },
                Icon('ant-design:appstore-outlined', 'color:var(--erd-color-primary);font-size:15px'),
                h('span', { style: css('font-size:12px;font-weight:500;color:var(--erd-color-text)') }, m.artifact),
                h('span', { style: css('margin-left:auto;font-size:11px;color:var(--erd-color-text-tertiary)') }, 'shown right →')) : null)))),
        V.cwGenerating ? h('div', null,
          h('div', { style: css('display:flex;align-items:center;gap:7px;margin-bottom:5px;font-size:11px;font-weight:600;color:var(--erd-color-text-secondary)') }, h(SparkleIcon, { size: 14, fill: 'var(--erd-color-primary)' }), 'eRD AI'),
          h('div', { style: css('max-width:92%;background:var(--erd-color-fill-tertiary);border-radius:14px 14px 14px 4px;padding:11px 13px') },
            h('div', { style: css('display:flex;align-items:center;gap:8px;font-size:12.5px;font-weight:500;color:var(--erd-color-text);margin-bottom:10px') }, h('span', { className: 'erd-spin', style: css('display:inline-flex;color:var(--erd-color-primary)') }, Icon('ant-design:loading-outlined', 'font-size:14px')), 'Working on it…'),
            h(ThoughtChain, { items: V.cwStepItemsLive }))) : null),

      // upload modal
      V.cwUploadOpen ? h('div', null,
        h('div', { onClick: V.cwCloseUpload, style: css('position:fixed;inset:0;background:var(--erd-color-bg-mask);z-index:50') }),
        h('div', { style: css('position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);width:520px;max-width:calc(100vw - 40px);max-height:calc(100vh - 60px);overflow-y:auto;background:#fff;border-radius:14px;box-shadow:0 12px 48px rgba(0,0,0,.2);z-index:51') },
          h('div', { style: css('padding:16px 20px;border-bottom:1px solid var(--erd-color-border-secondary);display:flex;align-items:center;justify-content:space-between') },
            h('div', { style: css('display:flex;align-items:center;gap:9px;font-weight:600;font-size:16px') }, Icon('ant-design:paper-clip-outlined', 'color:var(--erd-color-primary)'), 'Attach files'),
            h('span', { className: 'erd-icon-btn', onClick: V.cwCloseUpload, style: css('width:30px;height:30px;display:flex;align-items:center;justify-content:center;border-radius:7px;cursor:pointer;color:var(--erd-color-text-tertiary)') }, Icon('ant-design:close-outlined'))),
          h('div', { style: css('padding:18px 20px') },
            h('div', { onClick: V.cwBrowse, onDrop: V.cwDrop, onDragOver: V.cwDragOver, onDragEnter: V.cwDragOver, onDragLeave: V.cwDragLeave, style: V.cwDropzoneStyle },
              Icon('ant-design:cloud-upload-outlined', 'font-size:34px;color:var(--erd-color-primary)'),
              h('div', { style: css('font-size:13.5px;color:var(--erd-color-text);margin-top:8px') }, 'Drag & drop files here, or ', h('span', { style: css('color:var(--erd-color-primary);font-weight:600') }, 'browse')),
              h('div', { style: css('font-size:11.5px;color:var(--erd-color-text-tertiary);margin-top:5px') }, 'Up to 5 files · 5 GB total per chat · .xlsx .csv .txt and more')),
            h('input', { id: 'cwFileInput', type: 'file', multiple: true, onChange: V.cwPickFiles, style: { display: 'none' } }),
            V.cwUploadWarn ? h('div', { style: css('margin-top:12px;padding:9px 12px;background:var(--erd-color-warning-bg);border:1px solid var(--erd-color-warning-border);border-radius:8px;font-size:12px;color:#874d00;display:flex;align-items:center;gap:8px') }, Icon('ant-design:warning-outlined', 'color:var(--erd-color-warning)'), V.cwUploadWarn) : null,
            h('div', { style: css('display:flex;align-items:center;justify-content:space-between;margin:16px 0 8px') }, h('span', { style: css('font-size:12px;font-weight:600') }, 'Attached · ' + V.cwFileCount + '/5'), h('span', { style: css('font-size:11px;color:var(--erd-color-text-tertiary)') }, V.cwTotalSize + ' / 5 GB')),
            h('div', { style: css('display:flex;flex-direction:column;gap:7px;max-height:200px;overflow-y:auto') },
              V.cwFiles.map((f, i) => h('div', { key: i, style: css('display:flex;align-items:center;gap:10px;padding:9px 11px;border:1px solid var(--erd-color-border-secondary);border-radius:9px;background:var(--erd-color-fill-quaternary)') },
                Icon({ icon: f.icon, style: 'font-size:18px;color:' + f.color + ';flex:none' }),
                h('div', { style: css('flex:1;min-width:0') }, h('div', { style: css('font-size:13px;font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis') }, f.name), h('div', { style: css('font-size:11px;color:var(--erd-color-text-tertiary)') }, f.meta)),
                h('span', { className: 'erd-fav-remove', onClick: f.onRemove, style: css('width:22px;height:22px;display:flex;align-items:center;justify-content:center;border-radius:6px;color:var(--erd-color-text-quaternary);font-size:12px;cursor:pointer') }, Icon('ant-design:close-outlined')))),
              V.cwNoFiles ? h('div', { style: css('padding:14px;text-align:center;font-size:12px;color:var(--erd-color-text-tertiary)') }, 'No files yet.') : null)),
          h('div', { style: css('padding:14px 20px;border-top:1px solid var(--erd-color-border-secondary);display:flex;justify-content:flex-end') },
            h('div', { onClick: V.cwCloseUpload, style: css('height:36px;padding:0 20px;border-radius:8px;cursor:pointer;font-size:13px;font-weight:500;background:var(--erd-color-primary);color:#fff;display:flex;align-items:center') }, 'Done')))) : null,

      // composer footer
      h('div', { style: css('flex:none;padding:11px 20px 15px;border-top:1px solid var(--erd-color-border-secondary)') },
        h('div', { style: css('display:flex;flex-wrap:wrap;gap:6px;margin-bottom:10px') },
          h('div', { className: 'erd-tile', onClick: V.cwQuickSPC, style: css('font-size:12px;padding:5px 10px;border:1px solid var(--erd-color-border);border-radius:14px;cursor:pointer;color:var(--erd-color-text-secondary);background:#fff') }, 'SPC analysis'),
          h('div', { className: 'erd-tile', onClick: V.cwQuickPareto, style: css('font-size:12px;padding:5px 10px;border:1px solid var(--erd-color-border);border-radius:14px;cursor:pointer;color:var(--erd-color-text-secondary);background:#fff') }, 'Defect pareto'),
          h('div', { className: 'erd-tile', onClick: V.cwQuickTrend, style: css('font-size:12px;padding:5px 10px;border:1px solid var(--erd-color-border);border-radius:14px;cursor:pointer;color:var(--erd-color-text-secondary);background:#fff') }, 'Trend report'),
          h('div', { className: 'erd-tile', onClick: V.cwQuickSlides, style: css('font-size:12px;padding:5px 10px;border:1px solid var(--erd-color-primary-border);border-radius:14px;cursor:pointer;color:var(--erd-color-primary);background:var(--erd-color-primary-bg);display:inline-flex;align-items:center;gap:5px') }, Icon('ant-design:file-ppt-outlined'), 'Generate slides')),
        V.cwHasFiles ? h('div', { style: css('display:flex;flex-wrap:wrap;gap:6px;margin-bottom:8px') },
          V.cwFiles.map((f, i) => h('div', { key: i, style: css('display:inline-flex;align-items:center;gap:6px;max-width:190px;padding:4px 6px 4px 8px;border:1px solid var(--erd-color-border-secondary);border-radius:8px;background:var(--erd-color-fill-quaternary);font-size:11.5px') },
            Icon({ icon: f.icon, style: 'font-size:14px;color:' + f.color + ';flex:none' }),
            h('span', { style: css('white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--erd-color-text)') }, f.name),
            h('span', { className: 'erd-fav-remove', onClick: f.onRemove, style: css('width:16px;height:16px;display:flex;align-items:center;justify-content:center;border-radius:4px;color:var(--erd-color-text-quaternary);font-size:10px;cursor:pointer;flex:none') }, Icon('ant-design:close-outlined'))))) : null,
        h('div', { style: css('position:relative;display:flex;align-items:flex-end;gap:9px;border:1px solid var(--erd-color-border);border-radius:14px;padding:8px 8px 8px 10px;background:#fff') },
          h('div', { className: 'erd-icon-btn', onClick: V.cwPlusToggle, title: 'Add', style: css('width:30px;height:30px;display:flex;align-items:center;justify-content:center;border-radius:8px;cursor:pointer;color:var(--erd-color-text-secondary);font-size:18px;flex:none;margin-bottom:2px') }, Icon('ant-design:plus-outlined')),
          h('textarea', { value: V.cwInput, onChange: V.cwOnInput, onKeyDown: V.cwOnKey, placeholder: 'Ask eRD AI to analyze your data…  e.g. “build an SPC dashboard for Vt”', rows: 1, style: css('flex:1;border:none;outline:none;resize:none;font-family:inherit;font-size:13px;line-height:1.5;color:var(--erd-color-text);max-height:96px;padding:4px 0;background:transparent') }),
          h('div', { className: 'erd-icon-btn', onClick: V.cwSend, style: css('width:32px;height:32px;border-radius:9px;background:var(--erd-color-primary);color:#fff;display:flex;align-items:center;justify-content:center;cursor:pointer;flex:none') }, Icon('ant-design:arrow-up-outlined', 'font-size:16px')),
          V.cwPlusOpen ? h('div', null,
            h('div', { onClick: V.cwPlusClose, style: css('position:fixed;inset:0;z-index:35') }),
            h('div', { style: css('position:absolute;bottom:52px;left:4px;width:236px;background:#fff;border:1px solid var(--erd-color-border-secondary);border-radius:11px;box-shadow:0 6px 24px rgba(0,0,0,.14);z-index:40;overflow:hidden') },
              V.cwPlusRoot ? h('div', null,
                h('div', { className: 'erd-navrow', onClick: V.cwAttach, style: css('display:flex;align-items:center;gap:10px;padding:11px 14px;cursor:pointer;font-size:13px;color:var(--erd-color-text)') }, Icon('ant-design:paper-clip-outlined', 'font-size:16px;color:var(--erd-color-text-secondary)'), 'Attach file'),
                h('div', { className: 'erd-navrow', onClick: V.cwShowSources, style: css('display:flex;align-items:center;gap:10px;padding:11px 14px;cursor:pointer;font-size:13px;color:var(--erd-color-text);border-top:1px solid var(--erd-color-fill-quaternary)') }, Icon('ant-design:database-outlined', 'font-size:16px;color:var(--erd-color-text-secondary)'), 'Select data source', Icon('ant-design:right-outlined', 'margin-left:auto;font-size:11px;color:var(--erd-color-text-tertiary)'))) : null,
              V.cwPlusSources ? h('div', null,
                h('div', { className: 'erd-navrow', onClick: V.cwShowRoot, style: css('display:flex;align-items:center;gap:8px;padding:9px 14px;cursor:pointer;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.4px;color:var(--erd-color-text-tertiary);border-bottom:1px solid var(--erd-color-fill-quaternary)') }, Icon('ant-design:left-outlined'), 'Data source'),
                V.cwSourceList.map((src, i) => h('div', { key: i, className: 'erd-navrow', onClick: src.onPick, style: src.rowStyle }, Icon('ant-design:database-outlined', 'font-size:15px;color:var(--erd-color-text-tertiary)'), h('span', { style: css('flex:1') }, src.name), Icon({ icon: src.checkIcon, style: src.checkStyle })))) : null)) : null))),

    // ---- artifact column ----
    h('div', { style: css('flex:1;min-width:0;display:flex;flex-direction:column') },
      h('div', { style: css('flex:none;height:54px;display:flex;align-items:center;gap:14px;padding:0 20px;border-bottom:1px solid var(--erd-color-border-secondary);background:#fff') },
        h('div', { style: css('display:flex;align-items:center;gap:6px;font-size:13px;color:var(--erd-color-text-tertiary)') }, Icon('ant-design:thunderbolt-outlined', 'color:var(--erd-color-primary)'), 'Generated by eRD AI'),
        h('div', { style: css('display:flex;gap:4px;margin-left:6px;background:var(--erd-color-fill-tertiary);padding:3px;border-radius:9px') },
          h('div', { onClick: V.cwSetDash, style: V.cwDashTabStyle }, Icon('ant-design:dashboard-outlined'), 'Dashboard'),
          h('div', { onClick: V.cwSetSlides, style: V.cwSlidesTabStyle }, Icon('ant-design:file-ppt-outlined'), 'Slides')),
        h('div', { style: css('margin-left:auto;display:flex;align-items:center;gap:8px') },
          h('div', { className: 'erd-icon-btn', onClick: V.cwRegen, title: 'Regenerate', style: css('width:32px;height:32px;display:flex;align-items:center;justify-content:center;border-radius:8px;cursor:pointer;font-size:16px;color:var(--erd-color-text-secondary);border:1px solid var(--erd-color-border)') }, Icon('ant-design:reload-outlined')),
          h('div', { className: 'erd-icon-btn', onClick: V.cwOpenTab, title: 'Open the dashboard full-screen in a new tab', style: css('width:32px;height:32px;display:flex;align-items:center;justify-content:center;border-radius:8px;cursor:pointer;font-size:16px;background:var(--erd-color-primary);color:#fff') }, Icon('ant-design:export-outlined')))),
      h('div', { style: css('flex:1;overflow-y:auto;min-height:0;padding:20px') },
        V.cwEmpty ? h('div', { style: css('height:100%;min-height:360px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;color:var(--erd-color-text-tertiary)') },
          h('div', { style: css('width:56px;height:56px;border-radius:14px;background:var(--erd-color-primary-bg);color:var(--erd-color-primary);display:flex;align-items:center;justify-content:center;margin-bottom:14px') }, h(SparkleIcon, { size: 28, fill: 'currentColor' })),
          h('div', { style: css('font-size:15px;font-weight:600;color:var(--erd-color-text)') }, 'No artifact yet'),
          h('div', { style: css('font-size:13px;max-width:330px;margin-top:6px;line-height:1.5') }, 'Import your data on the left and ask eRD AI to build a dashboard or a deck — e.g. “Run an SPC analysis on Vt.”')) : null,
        V.cwShowDash ? h('div', null,
          h('div', { style: css('display:flex;align-items:baseline;gap:10px;margin-bottom:4px') }, h('h2', { style: css('margin:0;font-size:18px;font-weight:600') }, 'SPC analysis — Vt (gate CD)'), h('span', { style: css('font-size:12px;color:var(--erd-color-text-tertiary)') }, '24 lots · ' + V.cwSource)),
          h('div', { style: css('font-size:12.5px;color:var(--erd-color-text-secondary);margin-bottom:16px') }, 'Control chart with CL / ±3σ limits and Western Electric rules, defect pareto, and the Vt distribution.', h('span', { style: css('margin-left:8px;font-size:11px;color:var(--erd-color-text-tertiary);background:var(--erd-color-fill-tertiary);padding:2px 7px;border-radius:5px') }, 'Tailwind + ECharts')),
          h(SPCDashboard)) : null,
        V.cwShowSlides ? h('div', null,
          h('div', { style: css('display:flex;align-items:center;justify-content:space-between;margin-bottom:16px;flex-wrap:wrap;gap:10px') },
            h('div', null, h('h2', { style: css('margin:0;font-size:18px;font-weight:600') }, 'SPC deck · 4 slides'), h('div', { style: css('font-size:12.5px;color:var(--erd-color-text-secondary);margin-top:3px') }, 'Auto-generated from the SPC analysis. Edit or download as .pptx.')),
            h('div', { style: css('display:flex;gap:8px') },
              h('div', { className: 'erd-icon-btn', style: css('display:flex;align-items:center;gap:6px;height:34px;padding:0 13px;border-radius:8px;cursor:pointer;font-size:12.5px;color:var(--erd-color-text-secondary);border:1px solid var(--erd-color-border)') }, Icon('ant-design:edit-outlined'), 'Open in editor'),
              h('div', { className: 'erd-icon-btn', style: css('display:flex;align-items:center;gap:6px;height:34px;padding:0 14px;border-radius:8px;cursor:pointer;font-size:12.5px;font-weight:500;background:var(--erd-color-primary);color:#fff') }, Icon('ant-design:download-outlined'), 'Download .pptx'))),
          h('div', { style: css('display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:16px') },
            V.cwSlides.map((s, i) => h('div', { key: i, className: 'erd-tile', style: css('background:#fff;border:1px solid var(--erd-color-border-secondary);border-radius:10px;overflow:hidden;cursor:pointer;transition:all .15s') },
              h('div', { style: css('aspect-ratio:16/9;background:var(--erd-color-fill-quaternary);border-bottom:1px solid var(--erd-color-border-secondary);padding:16px;display:flex;flex-direction:column;position:relative') },
                h('div', { style: css('position:absolute;top:10px;right:12px;font-family:monospace;font-size:10px;color:var(--erd-color-text-quaternary)') }, s.n),
                h('div', { style: css('width:26px;height:3px;background:var(--erd-color-primary);border-radius:2px;margin-bottom:9px') }),
                h('div', { style: css('font-size:13px;font-weight:600;line-height:1.3;color:var(--erd-color-text)') }, s.title),
                h('div', { style: css('font-size:10.5px;color:var(--erd-color-text-tertiary);margin-top:5px') }, s.sub),
                h('div', { style: css('margin-top:auto;display:flex;gap:4px') }, h('div', { style: css('flex:1;height:5px;background:var(--erd-color-fill-secondary);border-radius:3px') }), h('div', { style: css('flex:1;height:5px;background:var(--erd-color-fill-secondary);border-radius:3px') }), h('div', { style: css('flex:2;height:5px;background:var(--erd-color-fill-tertiary);border-radius:3px') }))),
              h('div', { style: css('padding:9px 12px;font-size:11px;color:var(--erd-color-text-tertiary);display:flex;align-items:center;gap:6px') }, Icon('ant-design:file-ppt-outlined'), 'Slide ' + s.n))))) : null))
  )
}
