import { createElement as h } from 'react'
import { css } from '../lib/css'
import { SPCDashboard } from '../components/SPCDashboard'

/* Standalone full-screen dashboard — what Cowork's "Open new tab" loads
   (this page renders when the URL hash is #cowork-artifact). */
export function FullArtifact() {
  return h('div', { style: css('min-height:100vh;background:var(--erd-color-bg-layout);font-family:var(--erd-font-family);color:var(--erd-color-text)') },
    h('div', { style: css('height:56px;display:flex;align-items:center;gap:12px;padding:0 24px;background:#fff;border-bottom:1px solid var(--erd-color-border-secondary);position:sticky;top:0;z-index:5') },
      h('div', { style: css('width:30px;height:30px;border-radius:7px;background:var(--erd-color-primary);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:12px') }, 'eRD'),
      h('div', { style: css('font-weight:600;font-size:15px') }, 'SPC analysis — Vt (gate CD)'),
      h('span', { style: css('font-size:12px;color:var(--erd-color-text-tertiary)') }, 'Generated by eRD AI · 24 lots · Inline DB · N5 line')),
    h('div', { style: css('max-width:1320px;margin:0 auto;padding:24px 28px 48px') }, h(SPCDashboard)))
}
